
// Auto-generated by AutoPilot on 07-08-2023 at 00:45:08


const express = require('express');
const router = express.Router();

//Declaring the route
router.get('/grammy', (req, res) => {
    //Declaring an array with the last 5 Grammy Winners
    const grammyWinners = ['Billie Eilish','Kacey Musgraves','Childish Gambino','Drake','Bruno Mars'];
    
    //Responding with the array of Grammy Winners
    res.send(grammyWinners);
});

module.exports = router;